security-admin30:
    image: timeli/security-admin:latest
    container_name: security-admin30
    restart: always
    environment:
        - NODE_ENV=production
        - SDK_REST_URL=metadata.local:9000
    ports:
        - "3000:3000"
    external_links:
        - metadata30_stress:metadata.local
    labels:
        io.timeli.description: "Security user admin Application"
        io.timeli.service: "security-admin"
        io.timeli.applications: "security-admin"
